# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:25
from __future__ import unicode_literals

import crm.utils
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('contact', '0001_initial'),
        ('sprint', '0001_initial'),
        ('deal', '0001_initial'),
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('content', markdownx.models.MarkdownxField(blank=True, max_length=10000)),
                ('tosend_time', models.IntegerField(validators=[crm.utils.validate_epoch])),
                ('send_time', models.IntegerField(blank=True, null=True, validators=[crm.utils.validate_epoch])),
                ('channel', models.CharField(choices=[('TELEGRAM', 'TELEGRAM'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('INTERCOM', 'INTERCOM')], db_index=True, max_length=20)),
                ('require_confirmation', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deal.Deal')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='organization.Organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project.Project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sprint.Sprint')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='task.Task')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contact.Contact', verbose_name='contact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='message.Message', verbose_name='message')),
            ],
        ),
    ]
