DEBUG = True

SQLALCHEMY_DATABASE_URI = 'sqlite:///../db.dev'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = True
SQLALCHEMY_RECORD_QUERIES = True
SECRET_KEY = '%jkhds8866666YR3638*#@!&^%$!!!~~~~~loKo$ewQsdBnx'

