# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('deal', '0001_initial'),
        ('organization', '0001_initial'),
        ('task', '0001_initial'),
        ('project', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, db_index=True, max_length=10000)),
                ('url', models.URLField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='comment.Comment')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='contact.Contact', verbose_name='contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='deal.Deal', verbose_name='deal')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='organization.Organization', verbose_name='organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='project.Project', verbose_name='project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='task.Task', verbose_name='task')),
            ],
        ),
        migrations.CreateModel(
            name='LinkLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='link.Link', verbose_name='link')),
            ],
        ),
    ]
