# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:25
from __future__ import unicode_literals

import crm.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
        ('deal', '0001_initial'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('feature', 'feature'), ('question', 'question'), ('task', 'task'), ('story', 'contact'), ('contact', 'contact')], db_index=True, max_length=15)),
                ('description', markdownx.models.MarkdownxField(blank=True, db_index=True, max_length=10000)),
                ('urgency', models.CharField(choices=[('critical', 'critical'), ('urgent', 'urgent'), ('normal', 'normal'), ('minor', 'minor')], db_index=True, max_length=15)),
                ('time_todo', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='deal.Deal', verbose_name='deal')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organization.Organization', verbose_name='organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_owned_by', to='contact.Contact', verbose_name='owner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.Project', verbose_name='project')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sprint.Sprint', verbose_name='sprint')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('time_todo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='contact.Contact', verbose_name='contact')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task.Task', verbose_name='task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('remark', markdownx.models.MarkdownxField(blank=True, max_length=10000)),
                ('time_done', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('epoch', models.IntegerField(blank=True, validators=[crm.utils.validate_epoch])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='task.TaskAssignment', verbose_name='assignment')),
            ],
        ),
    ]
