"""empty message

Revision ID: 319951b3fda7
Revises: bf2d7df5ad1f
Create Date: 2018-02-01 14:06:25.755862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319951b3fda7'
down_revision = 'bf2d7df5ad1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_author_last_id_fkey', 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('messages_author_last_id_fkey', 'messages', 'users', ['author_last_id'], ['id'])
    # ### end Alembic commands ###
