"""empty message

Revision ID: 365fc573fcfb
Revises: 90021acc362d
Create Date: 2017-10-24 00:10:40.856408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365fc573fcfb'
down_revision = '90021acc362d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('event_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'event_id')
    # ### end Alembic commands ###
