"""empty message

Revision ID: 5964b8cfdffa
Revises: 38167d995c8b
Create Date: 2018-04-02 08:23:22.694004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5964b8cfdffa'
down_revision = '38167d995c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('migrated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'migrated')
    # ### end Alembic commands ###
