"""empty message

Revision ID: 90021acc362d
Revises: 88bd97fd024f
Create Date: 2017-10-23 15:58:45.016898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90021acc362d'
down_revision = '88bd97fd024f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_event_status', sa.Enum('INVITED', 'WONTSHOW', 'ATTENDED', 'DENIED', 'COULDNTMAKEIT', name='contacteventstatus'), nullable=True),
    sa.Column('event_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_description'), 'events', ['description'], unique=False)
    op.create_index(op.f('ix_events_event_datetime'), 'events', ['event_datetime'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('knowledgebase_categories',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebase_categories_name'), 'knowledgebase_categories', ['name'], unique=False)
    op.create_table('contacts_events',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledgebases',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=5), nullable=True),
    sa.Column('author_id', sa.String(length=5), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['knowledgebase_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebases_content'), 'knowledgebases', ['content'], unique=False)
    op.create_index(op.f('ix_knowledgebases_title'), 'knowledgebases', ['title'], unique=False)
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_country'), 'addresses', ['country'], unique=False)
    op.create_index(op.f('ix_addresses_description'), 'addresses', ['description'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_street_name'), 'addresses', ['street_name'], unique=False)
    op.create_index(op.f('ix_addresses_street_number'), 'addresses', ['street_number'], unique=False)
    op.create_index(op.f('ix_addresses_zip_code'), 'addresses', ['zip_code'], unique=False)
    op.add_column('comments', sa.Column('event_id', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('knowledge_base_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_comments_content'), 'comments', ['content'], unique=False)
    op.create_foreign_key(None, 'comments', 'knowledgebases', ['knowledge_base_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'events', ['event_id'], ['id'])
    op.create_index(op.f('ix_companies_description'), 'companies', ['description'], unique=False)
    op.create_index(op.f('ix_companies_emails'), 'companies', ['emails'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_telephones'), 'companies', ['telephones'], unique=False)
    op.create_index(op.f('ix_companies_vatnumber'), 'companies', ['vatnumber'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    op.create_index(op.f('ix_contacts_emails'), 'contacts', ['emails'], unique=False)
    op.create_index(op.f('ix_contacts_firstname'), 'contacts', ['firstname'], unique=False)
    op.create_index(op.f('ix_contacts_lastname'), 'contacts', ['lastname'], unique=False)
    op.create_index(op.f('ix_contacts_telephones'), 'contacts', ['telephones'], unique=False)
    op.create_index(op.f('ix_deals_amount'), 'deals', ['amount'], unique=False)
    op.create_index(op.f('ix_deals_currency'), 'deals', ['currency'], unique=False)
    op.create_index(op.f('ix_deals_deal_state'), 'deals', ['deal_state'], unique=False)
    op.create_index(op.f('ix_deals_deal_type'), 'deals', ['deal_type'], unique=False)
    op.create_index(op.f('ix_deals_is_paid'), 'deals', ['is_paid'], unique=False)
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index(op.f('ix_deals_referral_code'), 'deals', ['referral_code'], unique=False)
    op.add_column('links', sa.Column('event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_links_labels'), 'links', ['labels'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=False)
    op.create_foreign_key(None, 'links', 'events', ['event_id'], ['id'])
    op.add_column('messages', sa.Column('event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_content'), 'messages', ['content'], unique=False)
    op.create_index(op.f('ix_messages_title'), 'messages', ['title'], unique=False)
    op.create_foreign_key(None, 'messages', 'events', ['event_id'], ['id'])
    op.create_index(op.f('ix_organizations_description'), 'organizations', ['description'], unique=False)
    op.create_index(op.f('ix_organizations_emails'), 'organizations', ['emails'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_projects_deadline'), 'projects', ['deadline'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_index(op.f('ix_sprints_deadline'), 'sprints', ['deadline'], unique=False)
    op.create_index(op.f('ix_sprints_description'), 'sprints', ['description'], unique=False)
    op.create_index(op.f('ix_sprints_name'), 'sprints', ['name'], unique=False)
    op.create_index(op.f('ix_sprints_start_date'), 'sprints', ['start_date'], unique=False)
    op.create_index(op.f('ix_subgroups_groupname'), 'subgroups', ['groupname'], unique=False)
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=False)
    op.add_column('tasks', sa.Column('knowledge_base_id', sa.String(), nullable=True))
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'eta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.create_index(op.f('ix_tasks_eta'), 'tasks', ['eta'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_state'), 'tasks', ['state'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_type'), 'tasks', ['type'], unique=False)
    op.create_foreign_key(None, 'tasks', 'knowledgebases', ['knowledge_base_id'], ['id'])
    op.create_index(op.f('ix_users_emails'), 'users', ['emails'], unique=False)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_telephones'), 'users', ['telephones'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telephones'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_emails'), table_name='users')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_state'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_eta'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.alter_column('tasks', 'eta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('tasks', 'knowledge_base_id')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_index(op.f('ix_subgroups_groupname'), table_name='subgroups')
    op.drop_index(op.f('ix_sprints_start_date'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_name'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_description'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_deadline'), table_name='sprints')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_deadline'), table_name='projects')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_emails'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_description'), table_name='organizations')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_title'), table_name='messages')
    op.drop_index(op.f('ix_messages_content'), table_name='messages')
    op.drop_column('messages', 'event_id')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_labels'), table_name='links')
    op.drop_column('links', 'event_id')
    op.drop_index(op.f('ix_deals_referral_code'), table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_is_paid'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_type'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_state'), table_name='deals')
    op.drop_index(op.f('ix_deals_currency'), table_name='deals')
    op.drop_index(op.f('ix_deals_amount'), table_name='deals')
    op.drop_index(op.f('ix_contacts_telephones'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lastname'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_firstname'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_emails'), table_name='contacts')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_vatnumber'), table_name='companies')
    op.drop_index(op.f('ix_companies_telephones'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_emails'), table_name='companies')
    op.drop_index(op.f('ix_companies_description'), table_name='companies')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_content'), table_name='comments')
    op.drop_column('comments', 'knowledge_base_id')
    op.drop_column('comments', 'event_id')
    op.drop_index(op.f('ix_addresses_zip_code'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street_number'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street_name'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_description'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_country'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_index(op.f('ix_knowledgebases_title'), table_name='knowledgebases')
    op.drop_index(op.f('ix_knowledgebases_content'), table_name='knowledgebases')
    op.drop_table('knowledgebases')
    op.drop_table('contacts_events')
    op.drop_index(op.f('ix_knowledgebase_categories_name'), table_name='knowledgebase_categories')
    op.drop_table('knowledgebase_categories')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_event_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_description'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
