"""empty message

Revision ID: b6ea2b6c193a
Revises: 6d2cafaad793
Create Date: 2018-01-23 07:05:16.382949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ea2b6c193a'
down_revision = '6d2cafaad793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_rounds',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_rounds_end'), 'fund_rounds', ['end'], unique=False)
    op.create_index(op.f('ix_fund_rounds_start'), 'fund_rounds', ['start'], unique=False)
    op.create_index(op.f('ix_fund_rounds_target'), 'fund_rounds', ['target'], unique=False)
    op.create_index(op.f('ix_fund_rounds_title'), 'fund_rounds', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_rounds_title'), table_name='fund_rounds')
    op.drop_index(op.f('ix_fund_rounds_target'), table_name='fund_rounds')
    op.drop_index(op.f('ix_fund_rounds_start'), table_name='fund_rounds')
    op.drop_index(op.f('ix_fund_rounds_end'), table_name='fund_rounds')
    op.drop_table('fund_rounds')
    # ### end Alembic commands ###
