"""empty message

Revision ID: be4e863ec36f
Revises: 5964b8cfdffa
Create Date: 2018-04-17 07:23:46.103100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'be4e863ec36f'
down_revision = '5964b8cfdffa'
branch_labels = None
depends_on = None

old_dealtype = postgresql.ENUM('FARMER', 'HOSTER', 'ITO', 'PTO', 'AMBASSADOR', 'ITFT', 'PREPTO', name='dealtype')
new_dealtype = postgresql.ENUM('FARMER', 'HOSTER', 'ITO', 'PTO', 'AMBASSADOR', 'ITFT', 'PREPTO', 'TFT', name='dealtype')
temp_new_dealtype = postgresql.ENUM('FARMER', 'HOSTER', 'ITO', 'PTO', 'AMBASSADOR', 'ITFT', 'PREPTO', 'TFT', name='_dealtype')



def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    temp_new_dealtype.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE deals ALTER COLUMN deal_type TYPE _dealtype'
               ' USING deal_type::text::_dealtype')

    old_dealtype.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the "new" status type
    new_dealtype.create(op.get_bind(), checkfirst=False)

    op.execute('ALTER TABLE deals ALTER COLUMN deal_type TYPE dealtype'
               ' USING deal_type::text::dealtype')

    temp_new_dealtype.drop(op.get_bind(), checkfirst=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
