"""empty message

Revision ID: d81e2b9aa819
Revises: 
Create Date: 2018-02-11 14:44:23.052341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81e2b9aa819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('message_channels', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activities',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('type', sa.Enum('ISSUE_TF_APP', 'ISSUE_IYO', 'ISSUE_EXTRANET', 'INFO_WAITING', 'KYC', 'QUESTION_LEGAL', 'QUESTION_PROCESS', 'QUESTION_FINANCE', 'QUESTION', 'MEETING_WAITING', 'ZOOM_WAITING', name='activitytype'), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_type'), 'activities', ['type'], unique=True)
    op.create_table('companies',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vatnumber', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=5), nullable=True),
    sa.Column('ownerbackup_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ownerbackup_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_description'), 'companies', ['description'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_vatnumber'), 'companies', ['vatnumber'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    op.create_table('contacts',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('belief_statement', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('message_channels', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=5), nullable=True),
    sa.Column('ownerbackup_id', sa.String(length=5), nullable=True),
    sa.Column('parent_id', sa.String(length=5), nullable=True),
    sa.Column('tf_app', sa.Boolean(), nullable=True),
    sa.Column('tf_web', sa.Boolean(), nullable=True),
    sa.Column('referral_code', sa.String(length=255), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ownerbackup_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_firstname'), 'contacts', ['firstname'], unique=False)
    op.create_index(op.f('ix_contacts_gender'), 'contacts', ['gender'], unique=False)
    op.create_index(op.f('ix_contacts_lastname'), 'contacts', ['lastname'], unique=False)
    op.create_table('countries',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.Enum('DM', 'UG', 'IN', 'SH', 'UA', 'KH', 'TZ', 'GP', 'PN', 'BZ', 'PL', 'KG', 'SO', 'IS', 'AI', 'MY', 'NA', 'TJ', 'RU', 'GI', 'VG', 'MH', 'IE', 'DK', 'SN', 'PS', 'AS', 'RW', 'KI', 'GE', 'WS', 'LV', 'FM', 'NR', 'MZ', 'UZ', 'ZW', 'EG', 'FJ', 'BE', 'AT', 'RE', 'SC', 'TL', 'VC', 'PF', 'LY', 'TR', 'MC', 'CX', 'OM', 'AM', 'CC', 'LA', 'PG', 'BS', 'LC', 'CG', 'SA', 'PK', 'YT', 'DE', 'GY', 'KE', 'TN', 'AZ', 'SG', 'FR', 'KZ', 'GM', 'AD', 'LS', 'HN', 'PY', 'MP', 'HK', 'BO', 'LK', 'HR', 'CH', 'ML', 'MG', 'KR', 'BM', 'SJ', 'CL', 'PT', 'AG', 'KP', 'CN', 'SZ', 'MS', 'MA', 'CR', 'CZ', 'NU', 'ET', 'GT', 'IR', 'NL', 'JP', 'BR', 'TH', 'MT', 'CV', 'LR', 'MW', 'TO', 'SL', 'MN', 'BD', 'SV', 'BV', 'KN', 'IQ', 'AN', 'GA', 'KW', 'MD', 'CK', 'BH', 'JO', 'GR', 'ES', 'GN', 'CA', 'SK', 'SB', 'AF', 'QA', 'CU', 'GW', 'MO', 'LB', 'SR', 'DZ', 'IT', 'SI', 'TW', 'BA', 'BG', 'CO', 'AR', 'GF', 'CM', 'VU', 'GS', 'NG', 'VA', 'NF', 'PE', 'US', 'JM', 'KY', 'NE', 'BY', 'CS', 'KM', 'TK', 'PW', 'GD', 'AE', 'FI', 'AU', 'GU', 'UM', 'AW', 'NZ', 'RO', 'YE', 'CI', 'IL', 'AL', 'TT', 'SM', 'BF', 'EC', 'ST', 'GL', 'DJ', 'TF', 'TV', 'EH', 'VN', 'MK', 'PA', 'SD', 'AQ', 'HU', 'TG', 'FO', 'BW', 'EE', 'LU', 'LI', 'GQ', 'VE', 'FK', 'CF', 'BB', 'TC', 'NP', 'ID', 'PM', 'SY', 'TM', 'NC', 'GB', 'BN', 'TD', 'MQ', 'MU', 'CY', 'PH', 'BI', 'UY', 'NI', 'HT', 'SE', 'IO', 'BT', 'HM', 'LT', 'PR', 'MM', 'MX', 'VI', 'MR', 'NO', 'DO', 'BJ', 'GH', 'WF', 'CD', 'ER', 'ZM', 'ZA', 'AO', 'MV', name='countriesenum'), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('currencies',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=True)
    op.create_table('events',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_event_status', sa.Enum('INVITED', 'WONTSHOW', 'ATTENDED', 'DENIED', 'COULDNTMAKEIT', name='contacteventstatus'), nullable=True),
    sa.Column('event_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_description'), 'events', ['description'], unique=False)
    op.create_index(op.f('ix_events_event_datetime'), 'events', ['event_datetime'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('knowledgebase_categories',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebase_categories_name'), 'knowledgebase_categories', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=5), nullable=True),
    sa.Column('parent_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_description'), 'organizations', ['description'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('promoter_id', sa.String(length=5), nullable=True),
    sa.Column('guardian_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['promoter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_deadline'), 'projects', ['deadline'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_start_date'), 'projects', ['start_date'], unique=False)
    op.create_table('subgroups',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('groupname', sa.Enum('AMBASSADOR', 'INVESTOR', 'HOSTER', 'MEMBER', 'PUBLIC', name='subgroupname'), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgroups_groupname'), 'subgroups', ['groupname'], unique=False)
    op.create_table('tags',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=True)
    op.create_table('tasktrackings',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('time_done', sa.Integer(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies_contacts',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies_tags',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=5), nullable=True),
    sa.Column('company_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_activities',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_countries',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_events',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_projects',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('project_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts_subgroups',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency_id', sa.String(length=5), nullable=False),
    sa.Column('deal_type', sa.Enum('FARMER', 'HOSTER', 'ITO', 'PTO', 'AMBASSADOR', 'ITFT', 'PREPTO', name='dealtype'), nullable=False),
    sa.Column('deal_state', sa.Enum('NEW', 'INTERESTED', 'CONFIRMED', 'CREATED', 'SIGNED', 'PAID', 'CLOSED', 'LOST', name='dealstate'), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('company_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('referrer1_id', sa.String(length=5), nullable=True),
    sa.Column('owner_id', sa.String(length=5), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('referral_code', sa.String(length=255), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer1_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_deal_state'), 'deals', ['deal_state'], unique=False)
    op.create_index(op.f('ix_deals_deal_type'), 'deals', ['deal_type'], unique=False)
    op.create_index(op.f('ix_deals_is_paid'), 'deals', ['is_paid'], unique=False)
    op.create_index(op.f('ix_deals_name'), 'deals', ['name'], unique=False)
    op.create_index(op.f('ix_deals_referral_code'), 'deals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_deals_value'), 'deals', ['value'], unique=False)
    op.create_table('emails',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_email'), 'emails', ['email'], unique=True)
    op.create_table('images',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledgebases',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(length=5), nullable=True),
    sa.Column('author_id', sa.String(length=5), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['knowledgebase_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgebases_content'), 'knowledgebases', ['content'], unique=False)
    op.create_index(op.f('ix_knowledgebases_title'), 'knowledgebases', ['title'], unique=False)
    op.create_table('passports',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('passport_fullname', sa.String(length=255), nullable=False),
    sa.Column('passport_number', sa.Text(), nullable=False),
    sa.Column('issuance_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('country_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passports_passport_fullname'), 'passports', ['passport_fullname'], unique=False)
    op.create_index(op.f('ix_passports_passport_number'), 'passports', ['passport_number'], unique=False)
    op.create_table('phones',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_telephone'), 'phones', ['telephone'], unique=True)
    op.create_table('sprints',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('owner_id', sa.String(length=5), nullable=True),
    sa.Column('project_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_deadline'), 'sprints', ['deadline'], unique=False)
    op.create_index(op.f('ix_sprints_description'), 'sprints', ['description'], unique=False)
    op.create_index(op.f('ix_sprints_name'), 'sprints', ['name'], unique=False)
    op.create_index(op.f('ix_sprints_start_date'), 'sprints', ['start_date'], unique=False)
    op.create_table('users_organizations',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=5), nullable=True),
    sa.Column('organization_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('street_number', sa.String(length=255), nullable=True),
    sa.Column('street_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('company_id', sa.String(length=5), nullable=True),
    sa.Column('deal_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_description'), 'addresses', ['description'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_street_name'), 'addresses', ['street_name'], unique=False)
    op.create_index(op.f('ix_addresses_street_number'), 'addresses', ['street_number'], unique=False)
    op.create_index(op.f('ix_addresses_zip_code'), 'addresses', ['zip_code'], unique=False)
    op.create_table('contacts_sprints',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('sprint_id', sa.String(length=5), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TASK', 'FEATURE', 'QUESTION', 'STORY', 'CONTACT', name='tasktype'), nullable=True),
    sa.Column('priority', sa.Enum('MINOR', 'NORMAL', 'URGENT', 'CRITICAL', name='taskpriority'), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'PROGRESS', 'QUESTION', 'VERIFICATION', 'CLOSED', name='taskstate'), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('eta', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_estimate', sa.Integer(), nullable=True),
    sa.Column('time_done', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('sprint_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('knowledge_base_id', sa.String(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledgebases.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.create_index(op.f('ix_tasks_eta'), 'tasks', ['eta'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_state'), 'tasks', ['state'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_type'), 'tasks', ['type'], unique=False)
    op.create_table('messages',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('time_sent', sa.TIMESTAMP(), nullable=True),
    sa.Column('message_author_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('sprint_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('TOSEND', 'SENT', 'FAILED', name='messagestate'), nullable=True),
    sa.Column('parent_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_type', sa.Unicode(length=255), nullable=True),
    sa.Column('author_original_id', sa.Integer(), nullable=True),
    sa.Column('author_last_id', sa.Integer(), nullable=True),
    sa.Column('forced_destinations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['message_author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_content'), 'messages', ['content'], unique=False)
    op.create_index(op.f('ix_messages_state'), 'messages', ['state'], unique=False)
    op.create_index(op.f('ix_messages_title'), 'messages', ['title'], unique=False)
    op.create_table('links',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('sprint_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_labels'), 'links', ['labels'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=False)
    op.create_table('comments',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('company_id', sa.String(length=5), nullable=True),
    sa.Column('contact_id', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.String(length=5), nullable=True),
    sa.Column('deal_id', sa.String(length=5), nullable=True),
    sa.Column('task_id', sa.String(length=5), nullable=True),
    sa.Column('organization_id', sa.String(length=5), nullable=True),
    sa.Column('project_id', sa.String(length=5), nullable=True),
    sa.Column('sprint_id', sa.String(length=5), nullable=True),
    sa.Column('link_id', sa.String(length=5), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('knowledge_base_id', sa.String(), nullable=True),
    sa.Column('author_last_id', sa.String(length=5), nullable=True),
    sa.Column('author_original_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['author_last_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_original_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledgebases.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_content'), 'comments', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_content'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_labels'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_messages_title'), table_name='messages')
    op.drop_index(op.f('ix_messages_state'), table_name='messages')
    op.drop_index(op.f('ix_messages_content'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tasks_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_state'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_eta'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('contacts_sprints')
    op.drop_index(op.f('ix_addresses_zip_code'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street_number'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_street_name'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_description'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('users_organizations')
    op.drop_index(op.f('ix_sprints_start_date'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_name'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_description'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_deadline'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_phones_telephone'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_passports_passport_number'), table_name='passports')
    op.drop_index(op.f('ix_passports_passport_fullname'), table_name='passports')
    op.drop_table('passports')
    op.drop_index(op.f('ix_knowledgebases_title'), table_name='knowledgebases')
    op.drop_index(op.f('ix_knowledgebases_content'), table_name='knowledgebases')
    op.drop_table('knowledgebases')
    op.drop_table('images')
    op.drop_index(op.f('ix_emails_email'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_deals_value'), table_name='deals')
    op.drop_index(op.f('ix_deals_referral_code'), table_name='deals')
    op.drop_index(op.f('ix_deals_name'), table_name='deals')
    op.drop_index(op.f('ix_deals_is_paid'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_type'), table_name='deals')
    op.drop_index(op.f('ix_deals_deal_state'), table_name='deals')
    op.drop_table('deals')
    op.drop_table('contacts_subgroups')
    op.drop_table('contacts_projects')
    op.drop_table('contacts_events')
    op.drop_table('contacts_countries')
    op.drop_table('contacts_activities')
    op.drop_table('companies_tags')
    op.drop_table('companies_contacts')
    op.drop_table('tasktrackings')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subgroups_groupname'), table_name='subgroups')
    op.drop_table('subgroups')
    op.drop_index(op.f('ix_projects_start_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_deadline'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_description'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_knowledgebase_categories_name'), table_name='knowledgebase_categories')
    op.drop_table('knowledgebase_categories')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_event_datetime'), table_name='events')
    op.drop_index(op.f('ix_events_description'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_contacts_lastname'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_gender'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_firstname'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_vatnumber'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_description'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_activities_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
