# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 03:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=20)),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('description', markdownx.models.MarkdownxField(blank=True, db_index=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isuser', models.BooleanField(default=False, verbose_name='Is user?')),
                ('telegram', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Telegram bot')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_owned_by', to='contact.Contact')),
                ('owner_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_backedup_by', to='contact.Contact', verbose_name='Owner backup')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=40)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contact.Contact', verbose_name='contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contact.Contact', verbose_name='contact')),
            ],
        ),
        migrations.CreateModel(
            name='MessageChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('B', 'Bot'), ('E', 'Email'), ('T', 'Telephone'), ('S', 'SMS'), ('I', 'Intercome')], max_length=10)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_channels', to='contact.Contact')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messagechannel',
            unique_together=set([('channel', 'priority', 'contact')]),
        ),
    ]
